server:
  port: 8080

#Spring configs
spring:
    application:
        name: Packaging Manager Application
    main:
        allow-bean-definition-overriding: true
    devtools:
        add-properties: false
#jackson
    jackson:
        serialization:
            write-dates-as-timestamps: false


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
